### ISSUE TITLE
[Q] buildengine git repo ?

### ISSUE THREAD

**Issue by sparkleholic** [sailfishos/sailfish-qtcreator#152]
Hi, First of all, Thanks for the brilliant job and effort.
Could you give me a hint where I can get the sailfish-buildengine(scratchbox2) source ?
I found this (https://git.merproject.org/mer-core/scratchbox2/tree/master/scratchbox2) but I guess it seems to be old because I couldn't build this. It errors like the followings.
```
 fatal error: bits/libc-lock.h: No such file or directory
```
(This error may be related to the glibc version.)

**Comment by martyone** [comment]
Hi, the scratchbox2 sources you found are the current ones, but scratchbox2 is just one part of the build engine and one needs to use the toolchain that is part of the build engine to build it. Building full build engine is not a task one would like to do manually - this is normally done on infrastructure including an [Open Build Service](https://sailfishos.org/wiki/Open_Build_Service) instance and [Image Creator](https://sailfishos.org/wiki/Image_Creator) service. You can find more information on the wiki. More help you can get on Freenode channel #sailfishos.

**Comment by sparkleholic** [comment]
Thanks @martyone  :+1: 
I'll refer to the link you provided.

A few moments ago I was able to build the scratchbox2  in ubuntu 14.04. (Failed on ubunt 18.04.)
I would like to use a scratchbox and a different toolchain and sysroot than that of sailfishOS.
But it does not go as well as I thought.
I couldn't find good documents for scrachbox2.
Is there a separate guide for building BuildEngine locally without going through OpenBuildService?

**Comment by martyone** [comment]
This is the only document on sb2 I am aware of www.merproject.org/~lbt/SB2_internals_1st_ed_20120425.pdf. No other method of building that through OBS is used currently. Some older instructions could be found on the Mer project wiki.
