### ISSUE TITLE
Segfault when trying to add Desktop kit. 

### ISSUE THREAD

**Issue by bionade24** [sailfishos/sailfish-qtcreator#263]
```
Qt Creator 4.9.1 (Sailfish SDK 3.0.7)
```
Trying to add Desktop kit in the preferences. Qt5 is installed, the installation PATH of the System found. 
OS: Arch Linux, `qt5-base` installed.

**Comment by vigejolla** [comment]
I believe this is already fixed by commit 0df791da0333d3a621b3012d90d3db58e0e18f2b
