### ISSUE TITLE
Remove sdktool duplication

### ISSUE THREAD

**Issue by sergey-levin** [sailfishos/sailfish-qtcreator#283]
This line:
https://github.com/sailfishos/sailfish-qtcreator/blob/15480fc81d9adfaee0a767d896ee56417439ef4b/src/tools/tools.pro#L7
duplicates this line:
https://github.com/sailfishos/sailfish-qtcreator/blob/15480fc81d9adfaee0a767d896ee56417439ef4b/src/tools/tools.pro#L15

I think it was added accidentally by commit: [9e2643](https://github.com/sailfishos/sailfish-qtcreator/blob/9e264379b3f71ee21c3cb5a4d8ed1533dfbb3a41/src/tools/tools.pro#L5)

**Comment by martyone** [comment]
Thank you, fixed in master https://github.com/sailfishos/sailfish-qtcreator/commit/1c857e08da06d8b03297cab58e7f8adaf70f701f
